# Generated by Django 4.1 on 2022-08-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinfo',
            name='short_link',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_link.users')),
            ],
        ),
    ]
